name: 'Test'
on: #rebuild on PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'pipeline*'
jobs:
  test:
    runs-on:
      labels:
    steps:
      - uses: actions/checkout@v3
      - id: pytest
        uses: ./
      - run: echo 'Running pytest...'
